/** Textos UI del organigrama (misma experiencia que Software de Mejora). */
export const ORGANIGRAMA_LABELS: Record<string, string> = {
  pageTitle: "Organigrama",
  pageSubtitle:
    "Diagrama jerárquico con conectores (vista principal), lista administrativa y alta de nodos. Alineado a organigramas formales de obra y gestión.",
  treeTitle: "Árbol",
  emptyTree: "Sin nodos. Cree el primero en la pestaña «Nuevo».",
  newNodeTitle: "Nuevo nodo",
  placeholderName: "Nombre",
  placeholderRole: "Cargo / rol",
  parentRoot: "(Raíz)",
  parentUnder: "Bajo",
  placeholderEmail: "Correo",
  placeholderPhone: "Teléfono",
  createNode: "Crear nodo",
  inactive: "Inactivo",
  footerHint: "La edición vía API requiere rol de administrador.",
  backHome: "Volver al inicio",
  tabDiagram: "Diagrama",
  tabListAdmin: "Lista",
  tabNew: "Nuevo",
  diagramMetaToggle: "Leyenda y ayuda del lienzo",
  diagramMetaToggleHint: "opcional",
  diagramSectionTitle: "Vista principal — organigrama",
  diagramSectionHint:
    "Lienzo con zoom, ajuste a vista y arrastre directo. Clic en un nodo: selección (mover en sesión). Doble clic o Enter: abrir la ficha. Línea continua = jerarquía; línea punteada violeta = consultoría / enlace matricial hacia otro cargo.",
  consultantBadge: "Cons.",
  consultantLinkSection: "Consultoría / enlace matricial",
  consultantLinkHint:
    "Use esta opción para perfiles externos o consultoras que en la cartilla enlazan desde el costado de otra línea (no son el superior inmediato en el árbol). El nodo sigue colgando de su «superior» jerárquico; aquí elija el cargo al que se enlaza con línea punteada.",
  consultantLinkCurrent: "Enlazado a",
  consultantLinkSelect: "Enlazar a cargo (diagrama)",
  consultantLinkNone: "Sin enlace",
  newFormConsultantLink: "Enlace matricial / consultoría (opcional)",
  listHasConsultantLink: "Enlace matricial / consultoría",
  nodeDetailTitle: "Ficha de cargo",
  nodeDetailEmpty: "Seleccione un nodo en el diagrama.",
  listAdminTitle: "Vista lista administrativa",
  listAdminHint: "Misma jerarquía en formato compacto para revisión o soporte a RR.HH.",
  contactLine: "Contacto",
  statusLine: "Estado",
  statusActive: "Activo",
  zoomControls: "Escala",
  diagramPanHint:
    "Rueda: zoom. Arrastre el fondo: desplazar. Arrastre una tarjeta: mover en la sesión. Clic: seleccionar. Doble clic: editar ficha. Conexiones libres: clic en la línea para ajustar estilo (botón «Líneas» para alta y estilos globales).",
  toolbarZoomIn: "Acercar",
  toolbarZoomOut: "Alejar",
  toolbarFit: "Ajustar a vista",
  toolbarCenter: "Centrar",
  toolbarReset: "100%",
  toolbarCreate: "Nuevo nodo",
  toolbarList: "Vista lista",
  toolbarHelpTitle: "Uso del lienzo",
  toolbarHelpBody:
    "Rueda: zoom; arrastre el fondo: pan; arrastre tarjeta: mover en sesión. Clic en nodo: selección; doble clic: ficha. Botón «Líneas»: estilos jerárquicos/consultoría y conexiones libres. Clic en una conexión libre en el diagrama: barra compacta para color y trazo. «Ajustar a vista» encuadra todo.",
  toolbarSubUnderSelected: "Subordinado (selección)",
  toolbarDeselect: "Quitar selección",
  toolbarLinesButton: "Líneas",
  toolbarLinesTitle: "Estilos de línea y conexiones libres",
  linesModalTitle: "Líneas del organigrama",
  freeEdgeBarTitle: "Conexión libre",
  freeEdgeApply: "Aplicar",
  freeEdgeBarClose: "Listo",
  freeEdgeDeleteLink: "Eliminar enlace",
  freeEdgeBendDragHint:
    "Arrastre el punto azul en el tramo central para desplazar la línea (se guarda automáticamente al soltar).",
  freeEdgeDeleteNeedsRole:
    "Para eliminar o editar enlaces libres necesita rol Administrador. Puede ver la selección y cerrar con «Listo».",
  drawerClose: "Cerrar",
  levelLabel: "Nivel jerárquico",
  levelHint: "Profundidad en el árbol (referencia visual).",
  placeholderCategory: "Categoría / área",
  categoryHint: "Ej. Dirección, Operaciones…",
  photoUrlHint: "Use una URL https pública a la imagen. Para archivos locales, súbalos a su almacenamiento y pegue el enlace.",
  addSubordinate: "+ Crear subordinado",
  createSubordinate: "Crear subordinado",
  subFormHide: "Ocultar formulario",
  orgBandLevel: "Nivel {n}",
  noSecondaryContact: "Sin dato de contacto",
  superiorLabel: "Superior",
  subordinatesLabel: "Subordinados",
  orderLabel: "Orden",
  noSuperior: "— Raíz —",
  noSubordinates: "Sin subordinados directos.",
  placeholderPhotoUrl: "URL de foto (https://…)",
  saveNodeDetails: "Guardar ficha",
  savingNode: "Guardando…",
  reassignParent: "Reasignar superior",
  connectorPanelSummary: "Líneas del diagrama y conexiones libres",
  connectorPanelHint: "estilo Visio",
  connectorHierarchyTitle: "Líneas jerárquicas (superior → subordinado)",
  connectorAdvisoryTitle: "Líneas de consultoría / matricial (linkToId)",
  connectorColor: "Color",
  connectorWidth: "Grosor",
  connectorDashStyle: "Tipo",
  connectorDashSolid: "Continua",
  connectorDashDashed: "Rayada",
  connectorDashDotted: "Punteada",
  connectorFreeSection: "Conexión libre entre cargos (persistida)",
  connectorFrom: "Desde",
  connectorTo: "Hasta",
  connectorAdd: "Añadir conexión",
  connectorDelete: "Quitar",
  connectorEmptyEdges: "Sin conexiones libres. Elija dos cargos y pulse «Añadir conexión».",
  connectorReadOnly: "Solo lectura: no puede crear ni eliminar conexiones.",
};

export function formatOrgBandLevel(template: string, levelOneBased: string): string {
  return template.replace("{n}", levelOneBased);
}
